[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["cd backendpandacar && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd backendpandacar && python manage.py collectstatic --noinput"]

[start]
cmd = "cd backendpandacar && python manage.py migrate && gunicorn backendpandacar.wsgi:application --bind 0.0.0.0:$PORT"
